-- Keeping the events

ALTER TABLE EVENT DROP CONSTRAINT EVENT_FK_PROJECT;
ALTER TABLE EVENT DROP CONSTRAINT EVENT_FK_BRANCH;
ALTER TABLE EVENT DROP CONSTRAINT EVENT_FK_REQUEST;

ALTER TABLE EVENT ADD CONSTRAINT EVENT_FK_PROJECT FOREIGN KEY (PROJECT) REFERENCES PROJECT (ID) ON DELETE SET NULL;
ALTER TABLE EVENT ADD CONSTRAINT EVENT_FK_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID) ON DELETE SET NULL;
ALTER TABLE EVENT ADD CONSTRAINT EVENT_FK_REQUEST FOREIGN KEY (REQUEST) REFERENCES REQUEST (ID) ON DELETE SET NULL;
